input_data_path: "data/raw/sampled_train_50k.csv"
input_preprocessed_data_path: "data/raw/sampled_preprocessed_train_50k.csv"
output_model_path: "models/catclf.pkl"
output_transformer_path: "models/transformer.pkl"
output_ctr_transformer_path: "models/ctr_transformer.pkl"
metric_path: "models/metrics.json"
splitting_params:
  val_size: 0.2
  random_state: 42
train_params:
  model_type: "CatBoost"
  random_state: 42
  n_estimators: 50
  learning_rate: 0.05
  depth: 5
  bagging_temperature: 0.2
feature_params:
  count_features:
    - "device_ip_count"
    - "device_id_count"
    - "hour_of_day"
    - "day_of_week"
    - "hourly_user_count"
  ctr_features:
    - "site_id"
    - "site_domain"
    - "site_category"
    - "app_id"
    - "app_category"
    - "app_domain"
    - "device_model"
    - "device_type"
    - "device_conn_type"
    - "device_id_count"
    - "device_ip_count"
    - "banner_pos"
    - "C1"
    - "C14"
    - "C15"
    - "C16"
    - "C17"
    - "C18"
    - "C19"
    - "C20"
    - "C21"
    - "hour_of_day"
    - "day_of_week"
    - "hourly_user_count"
  target_col: 'click'
